// AUTO-GENERATED by scripts/build-profile.mjs — DO NOT EDIT BY HAND.
// Edit data/linkedin.pdf and/or data/hobbies.txt, then run: npm run build:profile

export const PROFILE_IS_PLACEHOLDER = false;

export const PROFILE = `## LinkedIn profile (education, certifications, experience, skills, projects)

Contact
sergeimaslennikov89@gmail.c
om
www.linkedin.com/in/sergei-
maslennikov-ai (LinkedIn)
huggingface.co/Neuromediator
(Portfolio)
github.com/Neuromediator
(Portfolio)
Top Skills
Data Analysis
LLM engineering
Python (Programming Language)
Certifications
Al Engineer Core Track: LLM
Engineering, RAG, QLORA, Agents
Google Data Analytics Specialization
Google Data Analytics Professional
Certificate (v2)
Sergei Maslennikov
LLM Engineer/ AI Practitioner focused on applied LLM systems |
Building RAG, agents & sports analytics
Tallinn, Harjumaa, Estonia
Summary
I build applied AI systems — RAG pipelines, agent workflows, LLM-
powered products. Currently shipping weekly: a workout tracker with
AI assistant (myfitnesspal.online), a Constitution of Estonia RAG
Q&amp;A, and an HR synthetic data generator. Before this, I spent
10 years (2014–2024) as an independent quantitative analyst in
sports markets — mainly tennis. The work: feature engineering from
match data, probabilistic decision-making with real money on the
line, continuous model evaluation under uncertainty. The skills that
came out of it — Bayesian reasoning, risk management, checking
whether a model is actually right or just looks right — transfer directly
to AI engineering. Bachelor of Marine Navigation from TalTech
Estonian Maritime Academy; worked briefly as a Deck Officer
before shifting to independent analysis. Stack: Python, LangChain/
LangGraph, OpenAI Agents SDK, FastAPI, Chroma, OpenAI &amp;
Anthropic APIs, OpenRouter, spec-driven development with Claude
Code and Cursor, SQL, React/TypeScript (learning) Open to AI
engineering / LLM roles — particularly at companies applying AI to
real business workflows. Especially happy to connect with builders
in Estonian AI
Experience
self directed
11 years 7 months
AI Implementer (Independent Projects)
December 2024 - Present (1 year 8 months)
Tallinn
Building and shipping applied LLM systems while transitioning into AI
engineering full-time.
Recent projects:
Page 1 of 2

-- 1 of 2 --

• Workout Tracker with AI Assistant — full-stack app deployed at
myfitnesspal.online. FastAPI + React/TypeScript + SQLite + LiteLLM/
OpenRouter/Cerebras. Built spec-first with Claude Code. [GitHub]
• Estonia Constitution RAG — document Q&A over the Estonian constitution.
Chroma vector DB, OpenAI embeddings, Gemini 2.0 Flash via OpenRouter,
grounded generation. [GitHub]
• HR Synthetic Data Generator — first accepted open-source PR to Ed
Donner's LLM Engineering course. Synthetic resumes and job postings for
NER, matching, and ATS pipeline testing. [GitHub]
Stack: Python, LangChain, FastAPI, Chroma, OpenAI & Anthropic APIs,
Claude Code, agent frameworks (MCP, tool use).
Independent Quantitative Analyst — Sports Markets
January 2015 - November 2024 (9 years 11 months)
Independent quantitative analyst in sports markets — primarily tennis and
volleyball. That was the work of reading thousands of matches, building
features from raw match data, and making probabilistic decisions with real
money on the line. It taught me Bayesian reasoning, risk management, and the
discipline of evaluating whether a model is actually correct or just looks correct
Hanjin Shipping Europe GmbH & Co KG
Deck Officer
July 2013 - December 2014 (1 year 6 months)
Navigation officer role following graduation from TalTech Estonian Maritime
Academy. Sea-going operations, watchkeeping, safety-critical decision-making
in high-responsibility environment.
Education
TalTech Estonian Maritime Academy
Bachelor of Marine Navigation · (September 2006 - July 2011)
Coursera
Google Data Analytics Professional Certificate (2025) · (May 2025 - October
2025)
Udemy ( instructor Ed Donner )
Al Engineer Core Track: LLM Engineering, RAG, QLORA, Agents · (October
2025 - February 2026)
Page 2 of 2

-- 2 of 2 --

---

## Hobbies & preferences

My name is Sergei Maslennikov. I'm an AI Practitioner and Data Analyst. I'm originally from Pärnu, a lovely  ultimate resort city in Estonia, now i am living in Tallinn.
I love healty food  and I am pasionate about sport. I like all kinds of functional training and gym activities`;
