// Build-time profile generator.
//
// Reads your LinkedIn export (data/linkedin.pdf) and a free-text hobbies file
// (data/hobbies.txt), extracts their text, and writes data/profile.generated.ts.
// That generated file is imported by the system prompt so the twin knows about you.
//
// Run manually whenever you update your PDF/txt:   npm run build:profile
// It also runs automatically before `npm run build` (see the "prebuild" script).
//
// Neither input file is required to build the app — if they're missing you get a
// clearly-marked placeholder profile so everything still compiles and runs.

import { readFile, writeFile, access } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PDF_PATH = path.join(root, "data", "linkedin.pdf");
const TXT_PATH = path.join(root, "data", "hobbies.txt");
const OUT_PATH = path.join(root, "data", "profile.generated.ts");

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function extractPdfText(buffer) {
  // pdf-parse v2 API: new PDFParse({ data }) -> getText() -> { text }
  const { PDFParse } = await import("pdf-parse");
  const parser = new PDFParse({ data: buffer });
  try {
    const result = await parser.getText();
    return (result.text || "").trim();
  } finally {
    await parser.destroy?.();
  }
}

// Collapse the noisy whitespace LinkedIn PDFs tend to produce.
function tidy(text) {
  return text
    .replace(/\r/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

const PLACEHOLDER = `## About
[Placeholder profile — add data/linkedin.pdf and data/hobbies.txt, then run \`npm run build:profile\`.]

I'm a professional happy to talk about my education, certifications, work
experience, skills, projects, hobbies, and how to get in touch.

## Experience
[No experience data yet — export your LinkedIn profile to PDF and drop it at data/linkedin.pdf.]

## Skills
[No skills data yet.]

## Hobbies & preferences
[No hobbies data yet — add data/hobbies.txt.]`;

async function main() {
  const sections = [];
  let usedPlaceholder = false;

  if (await exists(PDF_PATH)) {
    try {
      const buf = await readFile(PDF_PATH);
      const text = tidy(await extractPdfText(buf));
      if (text) {
        sections.push(`## LinkedIn profile (education, certifications, experience, skills, projects)\n\n${text}`);
        console.log(`[build-profile] Extracted ${text.length} chars from linkedin.pdf`);
      } else {
        console.warn("[build-profile] linkedin.pdf produced no text (scanned/image PDF?).");
      }
    } catch (err) {
      console.warn(`[build-profile] Failed to parse linkedin.pdf: ${err.message}`);
    }
  } else {
    console.warn("[build-profile] data/linkedin.pdf not found — skipping.");
  }

  if (await exists(TXT_PATH)) {
    const text = tidy(await readFile(TXT_PATH, "utf8"));
    if (text) {
      sections.push(`## Hobbies & preferences\n\n${text}`);
      console.log(`[build-profile] Read ${text.length} chars from hobbies.txt`);
    }
  } else {
    console.warn("[build-profile] data/hobbies.txt not found — skipping.");
  }

  let profile;
  if (sections.length === 0) {
    profile = PLACEHOLDER;
    usedPlaceholder = true;
    console.warn("[build-profile] No source files found — writing placeholder profile.");
  } else {
    profile = sections.join("\n\n---\n\n");
  }

  // Escape backticks and ${ so the content is safe inside a template literal.
  const escaped = profile.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

  const banner = `// AUTO-GENERATED by scripts/build-profile.mjs — DO NOT EDIT BY HAND.
// Edit data/linkedin.pdf and/or data/hobbies.txt, then run: npm run build:profile
`;

  const out = `${banner}
export const PROFILE_IS_PLACEHOLDER = ${usedPlaceholder};

export const PROFILE = \`${escaped}\`;
`;

  await writeFile(OUT_PATH, out, "utf8");
  console.log(`[build-profile] Wrote ${OUT_PATH}${usedPlaceholder ? " (placeholder)" : ""}`);
}

main().catch((err) => {
  console.error(`[build-profile] Fatal: ${err.stack || err.message}`);
  process.exit(1);
});
